development:
  adapter: postgresql
  encoding: unicode
  database: seurio_development
  pool: 5
  username: seurio
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: seurio_test
  pool: 5
  username: seurio
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: seurio_staging
  pool: 5
  username: seurio
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: seurio_production
  pool: 5
  username: seurio
  password:
